config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  #logout route
  delete '/logout' => 'sessions#destroy'
 
  #OMNI/AUTH CALLBACK ROUTE

  get '/auth/google_oauth2/callback' => 'sessions#google'

  delete '/schools/:id' => 'schools#destroy'

  resources :users 
  resources :schools do
   resources :playlists, only: [:new,:create,:index] #shallow routing
  end
  resources :playlists do
    resource :songs, only: [:new,:create,:index]
  end
  resources :songs

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  belongs_to :school
  has_many :songs 
  
  accepts_nested_attributes_for :songs
 
  validates :title, :events, presence: true
  validates :title, uniqueness: true
  validates :school_id, presence: true
  validates_associated :school

  scope :alpha, -> {order(:name) }


  def Limited
    today_limits = user.playlists.select do |c|
      c.created_at.try(:to_date) == Date.today
    end
    if today_limits.size > 2
    errors.add(:playlist_id, " can't be created past 2 daily. ")
    end
  end


end

app/models/school.rb
class School < ApplicationRecord
  has_many :playlists
  has_many :songs
  has_many :users, through: :playlists
  has_many :sorted_schools, -> {order_by_school}, class_name: 'School'
  
  validates :name, :city, :state, presence: true
  validates :name, :city, uniqueness: { case_sensitive: false }

  #scope :alpha, -> { order(:name) }
  scope :popular_schools, -> {joins(:playlists).group('school.id').order('count(schools.id) desc')}
end

app/models/song.rb
class Song < ActiveRecord::Base
    belongs_to :playlist
    belongs_to :user
    validates :artist, :tune, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schools
  has_many :playlists
  has_many :jams, through: :playlists, source: :school
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private

 def current_user
  @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
 end

 def logged_in?
  !!session[:user_id]
 end

 def redirect_if_not_signed_in
  redirect_to '/' if !logged_in? 
 end
end

app/controllers/playlists_controller.rb
require 'pry'

class PlaylistsController < ApplicationController

before_action :redirect_if_not_signed_in, :current_user, :stored_playlist, only:[:show, :edit, :update, :delete]


 def index
  if params[:school_id] && @school = School.find_by_id(params[:school_id])
    @playlists = @school.playlists.alpha
  else
    @error = "The School isn't created" if params[:school_id]
   @playlists = Playlist.alpha
  end
 end

 def new
  if params[:school_id] && @school = School.find_by_id(params[:school_id])
  #binding.pry
    @playlist = @school.playlists.build
  5.times {|i| @playlist.songs.build}
  else
    #binding.pry
   @playlist = Playlist.new
   5.times {|i| @playlist.songs.build}
  end
 end
  
 def create
   @playlist = current_user.playlists.build(playlist_params)
   @playlist.songs.each do |song|
    song.user = current_user
    @playlist.save
   end
   if @playlist.save
   redirect_to playlist_path(@playlist)
   else
    render :new
   end
 end

 def show
  #collect_playlist
 end

 def edit
  collect_playlist_alert
  
 end

 def update

 if @playlist.update(playlist_params)
  redirect_to playlist_path(@playlist)
  else
    render :edit
  end

 end


 def destroy
   @playlist = Playlist.find(params[:id])
  if @current_user.id == @playlist.user_id
   @playlist.destroy
   redirect_to playlists_path
  else
   flash[:message] = "Sorry, you did not create this"
   redirect_to '/playlists'
  end
 end


 private

 def collect_playlist_alert
    if !@playlist || @playlist.user != current_user
      flash[:message] = "This doesn't belong to you."
      redirect_to playlist_path 
    else
      render :edit
    end
 end

 def stored_playlist
  @playlist = Playlist.find_by(id: params[:id])
  redirect_to playlists_path if !@playlist
 end

 

 def playlist_params
  params.require(:playlist).permit(:user_id, :school_id, :title, :date, :events, songs_attributes: [ :id, :artist, :tune])
 end
end

app/controllers/schools_controller.rb
require 'pry'

class SchoolsController < ApplicationController

    before_action :redirect_if_not_signed_in, :current_user
    

 def new
 @school = School.new
 end

 def index
  @schools = School.all 
 end

 def create
    @school = School.create(school_params)
#binding.pry    
    if @school.save   
    redirect_to schools_path(@school)
    else
    render :new
    end
 end

 def show
    @school = School.find_by(id: params[:id])
 end

 def destroy
   @school = School.find(params[:id]) 
  if @current_user.id == @school.user_id
   @school.destroy
   redirect_to schools_path
  else
   flash[:message] = "Sorry, you did not create this"
   redirect_to '/schools'
  end
 end


 private

  def school_params
   params.require(:school).permit(:name, :city, :state, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def home
  end

  def create
   user = User.find_by(username: params[:user][:username])
   if user && user.authenticate(params[:user][:username])
       session[:user_id] = user.id
       redirect_to user_path(user)
   else
       flash[:message] = "Wrong login, try agan"
       redirect_to "/login"
    end    
  end

  def google
   @user = User.find_or_create_by(email: auth['info']['email']) do |user|
   user.username= auth['info']['first_name']
   user.password= SecureRandom.hex(16)
   end  
   if @user.save
     session[:user_id] = @user.id
     redirect_to user_path(@user)
   else
       redirect_to '/'
   end
  end
    
  def destroy
   session.clear
   redirect_to root_path
  end

  private
  
  def auth
   request.env['omniauth.auth']
  end
end

app/controllers/songs_controller.rb

class SongsController < ApplicationController
  before_action :redirect_if_not_logged_in, :current_user
  def show
     @song = Song.find_by_id(params[:id])

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

 def new
  @user = User.new
 end

 def create
    
   @user = User.new(user_params)
   if @user.save
    session[:user_id] = @user.id
    redirect_to @user
   else
      render :new
   end
 end
 
 def show
  redirect_if_not_signed_in
  @user = User.find_by_id(params[:id])
  redirect_to '/' if !@user
 end
  
   private
 def user_params
   params.require(:user).permit(:username, :email, :password)
 end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb

<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="topnav">

<nav>
    <ul>
    <h1>
    <div style="text-align: center;">
    <%= link_to "Home", root_path %> 
            
     <% if logged_in? %>
      <%= link_to "Logout", logout_path, method: "delete"%>
      <%= link_to "See playlist", playlists_path %>
      <%= link_to "Add School", new_school_path%>
      <%= link_to "See all the Schools", schools_path%>
     <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Log In", login_path %>
      <%= link_to "Log In with Google", '/auth/google_oauth2'%>
     <% end %>
        </div>
    </h1>
    </ul>
</nav>
</div>

app/views/layouts/_styling.html.erb

<head>
<style>
body {background-color: #1a0000;
 color: gray;
 font-family: "Times New Roman", Times, serif;
 font-size: 150%;
 text-align: center;
}
h1 {
  color: #ffffff;
  font-family: "Times New Roman", Times, serif;
  font-size: 150%;

}
h2 {
  color: #ffffff;
  font-family: "Times New Roman", Times, serif;
  font-size: 150%;

}
h3 {
  color: #ffffff;
  font-family: "Times New Roman", Times, serif;
  font-size: 150%;

}
</style>
</head>
<body>
<ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homecoming</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
       <%= render 'layouts/navbar' %>
       <%= render_flash_messages %>
    </div>
    <div>
      <% if flash[:message] %>
          <%= flash[:message]%>

      <% end %>
      <%= @error%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited  from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/playlists/_form.html.erb


   <% if @playlist.school %>
   <%= p.hidden_field :school_id %>
   
  <% else %>
    <%= p.label :school_id, "Find your School" %>
    <%= p.collection_select :school_id, School.all, :id, :name %>
  
   <% end %>



 <%= p.label :title, "Title" %>
 <%= p.text_field :title %>
 <br>
 <br>
 <%= p.label :date, "What day is it?" %>
 <%= p.date_field :date, {order: [:month, :day, :year], date_separator: "/", prompt: { month: 'mm', day: 'dd', year: 'yyyy'}, }%>
 <br>
 <br>
 <p> Songs  </p>
 <%= p.fields_for :songs do |jam| %>
    <%= jam.label :artist %> 
    <%= jam.text_field :artist %> 
   
    <%= jam.label :tune, "Title" %>
    <%= jam.text_field :tune %>
    <br>
 <% end %>
 <br>
 <br>
 <%= p.label :events, "When would you listen?"%>
 <%= p.text_area :events %>
 <br>

 <br>
 
 



app/views/playlists/edit.html.erb
<%= render 'layouts/styling' %>



<h1>Edit Playlist</h1>

<%= render partial: "layouts/errors", locals: {object: @playlist} %>
<%= form_for(@playlist) do |p|%>

  <%= render partial: 'playlists/form', locals: {p: p} %>


<%= p.submit %>
<% end %>

app/views/playlists/index.html.erb
<%= render 'layouts/styling' %>

<h1>All Playlist</h1>

<ul>
<% @playlists.each do |play| %>
<div>
<li><strong><%= link_to play.title, playlist_path(play)%>- <%= play.events %></strong></li>

</div>
<% end %>

</ul>

</div>

app/views/playlists/new.html.erb
<%= render 'layouts/styling' %>





<%= render partial: "layouts/errors", locals: {object: @playlist} %>


<% puts "Playlist: #{@playlist}" %>

<%= form_for(@playlist) do |p|%>

 <%= render partial: 'playlists/form', locals: {p: p} %>

 <%= p.hidden_field :user_id, :value => current_user.id %>

 <%= p.submit %>
<% end %>

app/views/playlists/show.html.erb
<%= render 'layouts/styling' %>


<h1><%= @playlist.school.name %>'s Playlist</h1>



<h1>Title :<%= @playlist.title %></h1>
<div>Date :<%= @playlist.date %></div>

 
<h2>Songs:</h2>
<% @playlist.songs.each do |jam| %>
  <li><%= jam.artist%> -<%=  jam.tune%></li>
<% end %>

<div><strong><h3> When would you listen to this ?</h3> <%= @playlist.events%></strong></div>
<br>
<br>
<% if @playlist.user == current_user %>
  <%= link_to "Edit Playlist", edit_playlist_path(@playlist) %>
  <%= button_to "Delete Playlist", playlist_path(@playlist), method: :delete  %>
  <%= link_to 'Back', schools_path %>
<% else %>
 <%= link_to 'Back', schools_path %>
<% end %>

</div>

app/views/schools/index.html.erb
<%= render 'layouts/styling' %>
<div style="text-align: center;">


<h1>All Schools</h1>

<br>
<% @schools.each do |sc|%>
 <li>
  <%= link_to sc.name, school_path(sc)%>
  </li>
<% end %>
</div>

app/views/schools/new.html.erb
<%= render 'layouts/styling' %>
<div style="text-align: center;">

<h1>Add a School</h1>
<%= render partial: "layouts/errors", locals: {object: @school} %>

<%= form_for(@school) do |s|%>

 <%= s.label :name %>
 <%= s.text_field :name %>
 <br>
 <br>
 <%= s.label :city %>
 <%= s.text_field :city %>
 <br>
 <br>
 <%= s.label :state %>
 <%= s.text_field :state %>
 <br>
 <br>
 <%= s.submit %>
<% end %>

app/views/schools/show.html.erb
<%= render 'layouts/styling' %>
<div style="text-align: center;">

<h1><%= @school.name %></h1>

<%= @school.city%>, <%= @school.state%>
<p><%= link_to "Delete School", school_path(@school), method: :delete %></p>
<p> <%= link_to "See All Playlists", school_playlists_path(@school)%> 
<p> <%= link_to "Add a Playlist", new_school_playlist_path(@school)%> 

<h2>Playlist Titles:</h2>
<% @school.playlists.each do |h|%>
<li><strong><%= link_to h.title, school_playlists_path(@school, h)%></li>
<% end %>
<br>
<br>
<%= link_to 'Back', schools_path %>

</div>


app/views/songs/new.html.erb
<%= render 'layouts/styling' %>


 <h1> Add Songs for <%= @song.playlist.title %></h1>

 <%= form_for [@playlist, @song] do |j|%>
   <%= j.hidden_field :playlist_id%>
   <div>
    <%= j.label :artist, "Artist"%>
    <%= j.text_field :artist%>
   </div>
 
   <div>
    <%= j.label :tune, "Name of the Song"%>
    <%= j.text_field :tune%>
   </div>
   <br>
   <%= f.submit %>
 <% end %>
</div>

app/views/songs/show.html.erb
<%= render 'layouts/styling' %>
<div style="text-align: center;">

<h1>Songs for <%= @playlist.title%></h1>
<ul>
<% @songs.each do |s|%>
<li><%= s.artist%>- <%= s.tune%> </li>
<% end %>
</ul>
</div>

app/views/users/new.html.erb
<%= render 'layouts/styling' %>

<div style="text-align: center;">

<h1>Sign up</h1>

<%= form_for(@user, url: '/signup') do |u| %>
  <%= u.label :username %>
  <%= u.text_field :username %>
  <br>
  <br>
  <%= u.label :email %>
  <%= u.email_field :email, required: true  %>
  <br>
  <br>
  <%= u.label :password %>
  <%= u.password_field :password %>
  <br>
  <br>
  <%= u.submit 'Submit' %>

<% end %>

app/views/users/show.html.erb
<%= render 'layouts/styling' %>

<div style="text-align: center;">

<h1>Welcome <%= @user.username %></h1>



<p> Feel free to add you college or university to share your Homecoming playlist. To begin click the on of the links in the navigation bar. Have fun , and enjoy as we share with each other in the Homecoming spirit!!</p>


  <%= image_tag("pic/grid.jpg", width: '700px')%>
</div>
</body>
</html> 